# Generated by Django 2.2 on 2023-01-30 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('status', models.CharField(default='Не оплачен', max_length=20, verbose_name='Статус заказа')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('mail', models.EmailField(max_length=50, verbose_name='Имэйл')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('delivery', models.CharField(max_length=100, verbose_name='Тип доставки')),
                ('pay', models.CharField(max_length=100, verbose_name='Тип оплаты')),
                ('comment', models.TextField(blank=True, default='', max_length=1000, verbose_name='Комментарий к заказу')),
                ('products', models.TextField(blank=True, default='', verbose_name='Список товаров')),
                ('total_price', models.IntegerField(default=0, verbose_name='Сумма заказа')),
                ('error', models.CharField(blank=True, default='', max_length=100, verbose_name='Текст ошибки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['created_at', 'status'],
            },
        ),
    ]
