# Generated by Django 2.2 on 2023-01-30 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('phone_number', models.CharField(blank=True, max_length=12, unique=True, verbose_name='Номер телефона')),
                ('money', models.IntegerField(default=0, verbose_name='Баланс')),
                ('is_active', models.CharField(choices=[('a', 'Активный'), ('n', 'Не активный')], default='a', max_length=1, verbose_name='Активность')),
                ('money_spend', models.IntegerField(default=0, verbose_name='Количество потраченных денег')),
                ('avatar', models.FileField(default='users/avatars/no_image.jpg', upload_to='users/avatars', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userprofile',
                'ordering': ['user'],
            },
        ),
    ]
