# Generated by Django 2.2 on 2023-01-30 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название товара')),
                ('is_active', models.BooleanField(default=False, verbose_name='активность')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название категории')),
                ('icon', models.FileField(default='assets/img/icons/departments/no_image.svg', upload_to='assets/img/icons/departments/', verbose_name='файл иконки')),
                ('is_active', models.BooleanField(default=False, verbose_name='активность')),
                ('sorting_index', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='индекс сортировки')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название магазина')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(max_length=256, verbose_name='url сайта')),
                ('title', models.CharField(max_length=256, verbose_name='название сайта')),
                ('cache', models.IntegerField(default=86400, verbose_name='время жизни кэша(сек)')),
                ('delivery_price', models.IntegerField(default=200, verbose_name='стоимость доставки(руб)')),
                ('free_delivery_from', models.IntegerField(default=2000, verbose_name='порог бесплатной доставки(руб)')),
                ('express_delivery_price', models.IntegerField(default=500, verbose_name='стоимость экспресс доставки(руб)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopToProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(default='assets/img/content/home/no_image.jpg', upload_to='assets/img/content/home/', verbose_name='файл иконки')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('amount', models.IntegerField(default=0, verbose_name='в наличии')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='скидка')),
                ('sold', models.IntegerField(default=0, verbose_name='продано')),
                ('reviews', models.IntegerField(default=0, verbose_name='обзоров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('sorting_index', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='индекс сортировки')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='краткое описание товара')),
                ('is_limited', models.BooleanField(default=False, verbose_name='ограниченный тираж»')),
                ('product_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shop.Product', verbose_name='товар')),
                ('shop_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shop.Shop', verbose_name='магазин')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('text', models.TextField(default='', max_length=1000, verbose_name='текст отзыва')),
                ('shop_to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.ShopToProduct', verbose_name='товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_shop.ProductCategory', verbose_name='категория товара'),
        ),
    ]
